#pragma once
#include <QHash>
#include <QMutex>
#include <QPair>
#include <QString>
#include <QVector>

// diablo4.dad database (d4dad.json) — the community transmog DB generated by
// github.com/diablo4dad/exporter from the same d4data export this tool consumes,
// but refreshed promptly after every game patch. Its per-class icon handles are
// the game's own hImageHandles (identical numbers to Item.tInvImages), so the
// tool resolves them to sprites itself via IconIndex/2D_table.dat.
//
// Used two ways:
//   1. Override/fill layer: the AppearanceMeta crawl fills icon handles the local
//      d4data snapshot is too stale to provide (item sno → per-class handles).
//   2. Reference for the hidden "Icon audit" (IconAudit.*): every appearance the
//      tool resolves is cross-checked against diablo4.dad's handles.
//
// The file is fetched with curl (same external-tool pattern as the d4data/TACT-key
// downloads — no QtNetwork in this build) into <AppData>/d4dad.json by MainWindow
// whenever the game/d4data fingerprint changes, and parsed lazily here.
struct DadItem {
    QString stem;      // item file stem, e.g. "Helm_Legendary_Generic_053"
    quint32 icon = 0;  // diablo4.dad's single "best" handle (fallback only)
    // Per eHeroClass {male/default, female} handles (empty when the item has none).
    QVector<QPair<quint32, quint32>> inv;
    // eHeroClass 0/1 usability mask. EMPTY = usable by all classes (the exporter
    // omits the field when every entry is 1). Lets the audit restrict which
    // appearances an item may claim (class-specific uniques share style numbers).
    QVector<quint8> usable;
};

class DadOverride {
public:
    static DadOverride& instance();
    // <AppData>/d4dad.json — where MainWindow's curl refresh drops the DB.
    static QString defaultPath();

    // Parse the cached DB once (thread-safe; the crawl worker and the audit both
    // call this). Returns true when item data is available.
    bool ensureLoaded();
    // Drop the parsed data so the next ensureLoaded() re-reads the file (called
    // after a successful re-download).
    void reset();

    // Item sno → DadItem. Only meaningful after ensureLoaded() returned true.
    const QHash<int, DadItem>& items() const { return m_items; }

private:
    DadOverride() = default;

    QMutex m_mutex;
    bool   m_parsed = false;
    QHash<int, DadItem> m_items;
};
